apiVersion: harness.io/v1
kind: Workflow
name: Hide Uploaded File in Review
identifier: hide-uploaded-file-in-review
type: service
metadata:
  description: Hide uploaded file contents in workflow review page.
spec:
  parameters:
    - title: Secure File Upload
      required:
        - uploaded_file
      properties:
        uploaded_file:
          title: Upload File
          type: string
          format: data-url
          description: Upload a file to be processed in the workflow.
          ui:backstage:
            review:
              show: false
              mask: true